version: '3'
services:
  web-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    tty: true
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/error:/var/log/nginx/
    ports:
      - "8000:80"
    networks:
      - app-net
  web-php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: web-php
    container_name: web-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - app-net
  web-postgres:
    image: postgres:12.6-alpine
    container_name: web-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker/postgres/data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-net
  web-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: web-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - app-net
  web-redis:
    image: redis
    container_name: web-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    command: redis-server --appendonly yes --requirepass thisisnotyourpasswd
    networks:
      - app-net
networks:
  app-net:
    driver: bridge



